<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="10" failures="0" hostname="LAPTOP-KL21T9AV" name="pytest" skipped="0" tests="10" time="0.902" timestamp="2020-07-14T16:27:51.338179"><testcase classname="" file="catalog/tests/test_models.py" name="catalog.tests.test_models" time="0.000"><error message="collection failure">catalog\tests\test_models.py:10: in &lt;module&gt;
    django.setup()
env\lib\site-packages\django\__init__.py:19: in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
env\lib\site-packages\django\conf\__init__.py:79: in __getattr__
    self._setup(name)
env\lib\site-packages\django\conf\__init__.py:66: in _setup
    self._wrapped = Settings(settings_module)
env\lib\site-packages\django\conf\__init__.py:157: in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
locallibrary\settings.py:28: in &lt;module&gt;
    ALLOWED_HOSTS = [testserver]
E   NameError: name &apos;testserver&apos; is not defined</error><error message="collection failure">catalog\tests\test_models.py:10: in &lt;module&gt;
    django.setup()
env\lib\site-packages\django\__init__.py:19: in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
env\lib\site-packages\django\conf\__init__.py:79: in __getattr__
    self._setup(name)
env\lib\site-packages\django\conf\__init__.py:66: in _setup
    self._wrapped = Settings(settings_module)
env\lib\site-packages\django\conf\__init__.py:157: in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
locallibrary\settings.py:28: in &lt;module&gt;
    ALLOWED_HOSTS = [testserver]
E   NameError: name &apos;testserver&apos; is not defined</error><error message="collection failure">catalog\tests\test_models.py:10: in &lt;module&gt;
    django.setup()
env\lib\site-packages\django\__init__.py:19: in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
env\lib\site-packages\django\conf\__init__.py:79: in __getattr__
    self._setup(name)
env\lib\site-packages\django\conf\__init__.py:66: in _setup
    self._wrapped = Settings(settings_module)
env\lib\site-packages\django\conf\__init__.py:157: in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
locallibrary\settings.py:28: in &lt;module&gt;
    ALLOWED_HOSTS = [testserver]
E   NameError: name &apos;testserver&apos; is not defined</error><error message="collection failure">catalog\tests\test_models.py:10: in &lt;module&gt;
    django.setup()
env\lib\site-packages\django\__init__.py:19: in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
env\lib\site-packages\django\conf\__init__.py:79: in __getattr__
    self._setup(name)
env\lib\site-packages\django\conf\__init__.py:66: in _setup
    self._wrapped = Settings(settings_module)
env\lib\site-packages\django\conf\__init__.py:157: in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
locallibrary\settings.py:28: in &lt;module&gt;
    ALLOWED_HOSTS = [testserver]
E   NameError: name &apos;testserver&apos; is not defined</error><error message="collection failure">catalog\tests\test_models.py:10: in &lt;module&gt;
    django.setup()
env\lib\site-packages\django\__init__.py:19: in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
env\lib\site-packages\django\conf\__init__.py:79: in __getattr__
    self._setup(name)
env\lib\site-packages\django\conf\__init__.py:66: in _setup
    self._wrapped = Settings(settings_module)
env\lib\site-packages\django\conf\__init__.py:157: in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
locallibrary\settings.py:28: in &lt;module&gt;
    ALLOWED_HOSTS = [testserver]
E   NameError: name &apos;testserver&apos; is not defined</error></testcase><testcase classname="" file="catalog/tests/test_views.py" name="catalog.tests.test_views" time="0.000"><error message="collection failure">catalog\tests\test_views.py:4: in &lt;module&gt;
    from catalog.models import Author
catalog\models.py:2: in &lt;module&gt;
    from django.contrib.auth.models import User
env\lib\site-packages\django\contrib\auth\models.py:2: in &lt;module&gt;
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
env\lib\site-packages\django\contrib\auth\base_user.py:47: in &lt;module&gt;
    class AbstractBaseUser(models.Model):
env\lib\site-packages\django\db\models\base.py:103: in __new__
    app_config = apps.get_containing_app_config(module)
env\lib\site-packages\django\apps\registry.py:252: in get_containing_app_config
    self.check_apps_ready()
env\lib\site-packages\django\apps\registry.py:134: in check_apps_ready
    settings.INSTALLED_APPS
env\lib\site-packages\django\conf\__init__.py:79: in __getattr__
    self._setup(name)
env\lib\site-packages\django\conf\__init__.py:66: in _setup
    self._wrapped = Settings(settings_module)
env\lib\site-packages\django\conf\__init__.py:157: in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
locallibrary\settings.py:28: in &lt;module&gt;
    ALLOWED_HOSTS = [testserver]
E   NameError: name &apos;testserver&apos; is not defined</error><error message="collection failure">catalog\tests\test_views.py:4: in &lt;module&gt;
    from catalog.models import Author
catalog\models.py:2: in &lt;module&gt;
    from django.contrib.auth.models import User
env\lib\site-packages\django\contrib\auth\models.py:2: in &lt;module&gt;
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
env\lib\site-packages\django\contrib\auth\base_user.py:47: in &lt;module&gt;
    class AbstractBaseUser(models.Model):
env\lib\site-packages\django\db\models\base.py:103: in __new__
    app_config = apps.get_containing_app_config(module)
env\lib\site-packages\django\apps\registry.py:252: in get_containing_app_config
    self.check_apps_ready()
env\lib\site-packages\django\apps\registry.py:134: in check_apps_ready
    settings.INSTALLED_APPS
env\lib\site-packages\django\conf\__init__.py:79: in __getattr__
    self._setup(name)
env\lib\site-packages\django\conf\__init__.py:66: in _setup
    self._wrapped = Settings(settings_module)
env\lib\site-packages\django\conf\__init__.py:157: in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
locallibrary\settings.py:28: in &lt;module&gt;
    ALLOWED_HOSTS = [testserver]
E   NameError: name &apos;testserver&apos; is not defined</error><error message="collection failure">catalog\tests\test_views.py:4: in &lt;module&gt;
    from catalog.models import Author
catalog\models.py:2: in &lt;module&gt;
    from django.contrib.auth.models import User
env\lib\site-packages\django\contrib\auth\models.py:2: in &lt;module&gt;
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
env\lib\site-packages\django\contrib\auth\base_user.py:47: in &lt;module&gt;
    class AbstractBaseUser(models.Model):
env\lib\site-packages\django\db\models\base.py:103: in __new__
    app_config = apps.get_containing_app_config(module)
env\lib\site-packages\django\apps\registry.py:252: in get_containing_app_config
    self.check_apps_ready()
env\lib\site-packages\django\apps\registry.py:134: in check_apps_ready
    settings.INSTALLED_APPS
env\lib\site-packages\django\conf\__init__.py:79: in __getattr__
    self._setup(name)
env\lib\site-packages\django\conf\__init__.py:66: in _setup
    self._wrapped = Settings(settings_module)
env\lib\site-packages\django\conf\__init__.py:157: in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
locallibrary\settings.py:28: in &lt;module&gt;
    ALLOWED_HOSTS = [testserver]
E   NameError: name &apos;testserver&apos; is not defined</error><error message="collection failure">catalog\tests\test_views.py:4: in &lt;module&gt;
    from catalog.models import Author
catalog\models.py:2: in &lt;module&gt;
    from django.contrib.auth.models import User
env\lib\site-packages\django\contrib\auth\models.py:2: in &lt;module&gt;
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
env\lib\site-packages\django\contrib\auth\base_user.py:47: in &lt;module&gt;
    class AbstractBaseUser(models.Model):
env\lib\site-packages\django\db\models\base.py:103: in __new__
    app_config = apps.get_containing_app_config(module)
env\lib\site-packages\django\apps\registry.py:252: in get_containing_app_config
    self.check_apps_ready()
env\lib\site-packages\django\apps\registry.py:134: in check_apps_ready
    settings.INSTALLED_APPS
env\lib\site-packages\django\conf\__init__.py:79: in __getattr__
    self._setup(name)
env\lib\site-packages\django\conf\__init__.py:66: in _setup
    self._wrapped = Settings(settings_module)
env\lib\site-packages\django\conf\__init__.py:157: in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
locallibrary\settings.py:28: in &lt;module&gt;
    ALLOWED_HOSTS = [testserver]
E   NameError: name &apos;testserver&apos; is not defined</error><error message="collection failure">catalog\tests\test_views.py:4: in &lt;module&gt;
    from catalog.models import Author
catalog\models.py:2: in &lt;module&gt;
    from django.contrib.auth.models import User
env\lib\site-packages\django\contrib\auth\models.py:2: in &lt;module&gt;
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
env\lib\site-packages\django\contrib\auth\base_user.py:47: in &lt;module&gt;
    class AbstractBaseUser(models.Model):
env\lib\site-packages\django\db\models\base.py:103: in __new__
    app_config = apps.get_containing_app_config(module)
env\lib\site-packages\django\apps\registry.py:252: in get_containing_app_config
    self.check_apps_ready()
env\lib\site-packages\django\apps\registry.py:134: in check_apps_ready
    settings.INSTALLED_APPS
env\lib\site-packages\django\conf\__init__.py:79: in __getattr__
    self._setup(name)
env\lib\site-packages\django\conf\__init__.py:66: in _setup
    self._wrapped = Settings(settings_module)
env\lib\site-packages\django\conf\__init__.py:157: in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
locallibrary\settings.py:28: in &lt;module&gt;
    ALLOWED_HOSTS = [testserver]
E   NameError: name &apos;testserver&apos; is not defined</error></testcase></testsuite></testsuites>