<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="3" hostname="LAPTOP-KL21T9AV" name="pytest" skipped="0" tests="16" time="1.222" timestamp="2020-07-15T11:01:09.239973"><testcase classname="catalog.tests.test_forms.RenewBookFormTest" file="catalog\tests\test_forms.py" line="12" name="test_renew_form_date_field_help_text" time="0.004"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="catalog.tests.test_forms.RenewBookFormTest" file="catalog\tests\test_forms.py" line="8" name="test_renew_form_date_field_label" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="catalog.tests.test_forms.RenewBookFormTest" file="catalog\tests\test_forms.py" line="16" name="test_renew_form_date_in_past" time="0.002"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="catalog.tests.test_forms.RenewBookFormTest" file="catalog\tests\test_forms.py" line="31" name="test_renew_form_date_max" time="0.085"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="catalog.tests.test_forms.RenewBookFormTest" file="catalog\tests\test_forms.py" line="26" name="test_renew_form_date_today" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="catalog.tests.test_forms.RenewBookFormTest" file="catalog\tests\test_forms.py" line="21" name="test_renew_form_date_too_far_in_future" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="catalog.tests.test_models.AuthorModelTest" file="catalog\tests\test_models.py" line="23" name="test_date_of_death_label" time="0.010"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="catalog.tests.test_models.AuthorModelTest" file="catalog\tests\test_models.py" line="18" name="test_first_name_label" time="0.003"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="catalog.tests.test_models.AuthorModelTest" file="catalog\tests\test_models.py" line="28" name="test_first_name_max_length" time="0.003"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="catalog.tests.test_models.AuthorModelTest" file="catalog\tests\test_models.py" line="38" name="test_get_absolute_url" time="0.030"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="catalog.tests.test_models.AuthorModelTest" file="catalog\tests\test_models.py" line="33" name="test_object_name_is_last_name_comma_first_name" time="0.004"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="catalog.tests.test_views.AuthorListViewTest" file="catalog\tests\test_views.py" line="37" name="test_lists_all_authors" time="0.073"><failure message="TypeError: argument of type &apos;NoneType&apos; is not iterable">self = &lt;catalog.tests.test_views.AuthorListViewTest testMethod=test_lists_all_authors&gt;

    def test_lists_all_authors(self):
        # Get second page and confirm it has (exactly) remaining 3 items
        response = self.client.get(reverse(&apos;authors&apos;)+&apos;?page=2&apos;)
        self.assertEqual(response.status_code, 200)
&gt;       self.assertTrue(&apos;is_paginated&apos; in response.context)
E       TypeError: argument of type &apos;NoneType&apos; is not iterable

catalog\tests\test_views.py:42: TypeError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="catalog.tests.test_views.AuthorListViewTest" file="catalog\tests\test_views.py" line="30" name="test_pagination_is_ten" time="0.009"><failure message="TypeError: argument of type &apos;NoneType&apos; is not iterable">self = &lt;catalog.tests.test_views.AuthorListViewTest testMethod=test_pagination_is_ten&gt;

    def test_pagination_is_ten(self):
        response = self.client.get(reverse(&apos;authors&apos;))
        self.assertEqual(response.status_code, 200)
&gt;       self.assertTrue(&apos;is_paginated&apos; in response.context)
E       TypeError: argument of type &apos;NoneType&apos; is not iterable

catalog\tests\test_views.py:34: TypeError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="catalog.tests.test_views.AuthorListViewTest" file="catalog\tests\test_views.py" line="21" name="test_view_url_accessible_by_name" time="0.008"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="catalog.tests.test_views.AuthorListViewTest" file="catalog\tests\test_views.py" line="17" name="test_view_url_exists_at_desired_location" time="0.008"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="catalog.tests.test_views.AuthorListViewTest" file="catalog\tests\test_views.py" line="25" name="test_view_uses_correct_template" time="0.011"><failure message="AssertionError: No templates used to render the response">self = &lt;catalog.tests.test_views.AuthorListViewTest testMethod=test_view_uses_correct_template&gt;

    def test_view_uses_correct_template(self):
        response = self.client.get(reverse(&apos;authors&apos;))
        self.assertEqual(response.status_code, 200)
&gt;       self.assertTemplateUsed(response, &apos;/catalog/author_list.html&apos;)

catalog\tests\test_views.py:29: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
env\lib\site-packages\django\test\testcases.py:639: in assertTemplateUsed
    self.fail(msg_prefix + &quot;No templates used to render the response&quot;)
E   AssertionError: No templates used to render the response</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>